### ISSUE TITLE
Not refreshing code with mocha --watch

### ISSUE THREAD

**Issue by markogresak** [blakeembrey/typescript-node#9]
I've tried to use this module as `mocha --compilers tsx:typescript-node/register` and it works great, but when I add `--watch`, it will always run the same code as the first run of mocha. I suspect it's caching the compiled files and not recompiling until running again. 

I'm using it with `typescript@next` (1.6.0-dev.20150908) and `.tsx` files (for JSX support).

When I was using babel compiler for my js tests, `--compilers js:babel/register`, was working fine.

**Comment by blakeembrey** [comment]
Thanks for the report! Yes, you are correct - files are currently being cached in memory. I'll have a patch tonight, so I'll keep you posted in this issue.

**Comment by blakeembrey** [comment]
@markogresak Could you try the latest release, `v0.0.9` - it uses the version (mtime) of the file to check for updates.

**Comment by markogresak** [comment]
It's working now, thanks!
